### ISSUE TITLE
problema

### ISSUE THREAD

**Issue by otreboravlis** [creactivebr/sigaalua#2]
Não to mais conseguindo entrar no sigaa por ele.

**Comment by hermanocabral** [comment]
Qual erro que aparece qd vc tenta logar?

**Comment by otreboravlis** [comment]
[image: image.png]

Em qua, 17 de out de 2018 às 18:18, HCN <notifications@github.com> escreveu:

**Comment by ssisaias** [comment]
![image](https://user-images.githubusercontent.com/3528085/47762816-f0565a00-dc9c-11e8-8ba3-306f26d8b10d.png)

Aparentemente também removeram a mensagem que impedia de logar pelo chrome nessa página.

**Comment by brunosaboia** [comment]
@ssisaias , exatamente. Agora voce pode fazer login direto.

@otreboravlis O problema ja deve estar solucionado agora, por favor verifique. Mas note, como eu disse acima, que e' possivel fazer login diretamente
